stages:
- name: compi;e
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test
      pushRemote: true
      registry: 127.0.0.1:34252
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
